### ISSUE TITLE
how can i save my documents?

### ISSUE THREAD

**Issue by Amonisis36** [wangyao1052/LitCAD#1]
dear author,
       thank you for your LitCAD, I can try some drawing tasks.
       I have a question here, that how can i save my documents when it got finished.
       what kind of file type can I use for save as?

**Comment by Amonisis36** [comment]
作者您好，
       感谢您开源的LitCAD, 有一些简单任务我现在可以独立完成了。
       想要咨询的是，当我完成一个document的绘制以后，怎么进行保存？是否可以存储为autoCAD可以打开的文件，或者jpg格式的图片？
       盼复

**Comment by wangyao1052** [comment]
之前没有关注过issue。
目前LitCAD的文件可以存成XML格式的文件.litcad。
可以通过菜单命令【文件】->【保存】来执行。
